language: go

go:
  - 1.6.2
  - tip
  
before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  
script:
  - diff -u <(echo -n) <(gofmt -d -s .)
  - go tool vet .
  - go test -v -race .
  - $HOME/gopath/bin/goveralls -service=travis-ci